### ISSUE TITLE
edit a list of objects

### ISSUE THREAD

**Issue by johannchen** [JackAdams/meteor-editable-list#1]
Is it possible to edit a list of objects? for instance
{ _id: xxx, name: "test", posts: [ {title: "t1", content: "c1"}, {title: "t2", content: "c2"}] }
Is it possible to edit each object in posts?

**Comment by JackAdams** [comment]
No, it's very much just a UI widget for manipulating an array of strings.  It would take significant refactoring to make it able to edit objects.  I do like the idea though.
