### ISSUE TITLE
userCanEdit does nothing?

### ISSUE THREAD

**Issue by ryanswrt** [JackAdams/meteor-editable-list#3]
I've added a function to determine whether a user can edit the list or not, and it works for the EditableText template, but it doesn't seem to have any effect on the list widget. If I override the server method, it denies updates as expected, but the input widget is still there and the user can still edit items at will.

**Comment by JackAdams** [comment]
Yes, you're right.  Thank you for highlighting the issue.  Just released a new version that should fix that.

**Comment by ryanswrt** [comment]
Awesome, thanks.
